-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgURk75+xcUsJkh6Cf
spTXZ0mxUQJddRg+BTFB5JhrSyWgCgYIKoZIzj0DAQehRANCAASP9Qu0tOEoEuT1
Gs8lB/X+XvpueTLlrO19DRUnkZOYUghy2v0OK6OFEQvh1TZIN0uUGUtJJJPXC2q4
Cg1jo/Zd
-----END PRIVATE KEY-----